### ISSUE TITLE
Incorrect public key derivation from signature

### ISSUE THREAD

**Issue by vimwitch** [personaelabs/efficient-zk-ecdsa#18]
If the private key `0x00554c162e41ab505bc0cc0818fc53940a9687dda3120cf7057576b32ed65344` is used to sign the message "hello world" the public key will be incorrectly recovered in zk.

Reproduce by replacing the private key [here](https://github.com/personaelabs/efficient-zk-ecdsa/blob/main/scripts/build_ecdsa_verify_pubkey_to_addr/ecdsa_verify_pubkey_to_addr.js#L16) with the one above, then run the package scripts.

Replacing `Secp256K1ScalarMultCachedWindowed` with `Secp256k1ScalarMult` in the ecdsa proof solves the problem.

**Comment by DanTehrani** [comment]
Fixed: https://github.com/personaelabs/efficient-zk-ecdsa/commit/3899bfbfe1e4ab296d5e4bd0aede2aa54b6044f4

thanks for reporting @vimwitch !
